---
- name: Obtengo las imagenes de Kubeadmn
  command: 'kubeadm init --pod-network-cidr {{ master_range_ip }}'
  register: result
  become: yes
  become_method: sudo

- debug:
    msg: '{{ result }}'
