---

#- name: Cambio permisos a root
#  environment:
#    KUBECONFIG: /etc/kubernetes/admin.conf
#  file:
#    path: /etc/kubernetes/admin.conf
#  become: yes
#  become_method: sudo

- name: populate /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "KUBECONFIG="
    line: " KUBECONFIG=/etc/kubernetes/admin.conf"
  become: yes
  become_method: sudo


- name: Creo directorios /root/.kube
  file:
    path: /root/.kube
    state: directory
  become: yes
  become_method: sudo


- name: Copio archivo configuracion
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
  become: yes
  become_method: sudo
