---

- name: Token
  command: 'kubeadm token create --print-join-command'
  register: kubeadm_out

- name: archivo token.conf
  local_action: copy content="{{ kubeadm_out.stdout_lines[0] }}" dest="{{ file_token }}"

- name: Reiniciar equipo
  reboot:
    msg: "Reinicio post instalacion"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: true
  become_method: sudo