---
- name: Confifuramos masquerade
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true
  become: yes
  become_method: sudo

- name: 'Copio archivo para config k8s.conf'
  copy:
    src: 'k8s.conf'
    dest: '/etc/sysctl.d/'
  become: yes
  become_method: sudo

- name: Reiniciamos el firewall
  shell: firewall-cmd --reload
  become: yes
  become_method: sudo
