---
- include_tasks: 01-config_modprobe.yaml

- include_tasks: 02-config_firewall.yaml

- include_tasks: 03-config_swap.yaml

#- include_tasks: 04-install_crio.yaml
#  vars:
#    repos:
#      - repo_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo'
#        repo_dest: '/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo'
#      - repo_url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo'
#        repo_dest: '/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo'

- include_tasks: 04-install_docker.yaml
  vars:
    repos:
      - repo_url: 'https://download.docker.com/linux/centos/docker-ce.repo'
        repo_dest: '/etc/yum.repos.d/docker-ce.repo'

- include_tasks: 05-install_Kube.yaml
