---

- name: 'Copio archivo Deploy volumen.yaml'
  copy:
    src: 'volumen.yaml'
    dest: '/tmp/jenkins/'
  become: yes
  become_method: sudo


- name: Despliego Volumens
  command: 'kubectl apply -f /tmp/jenkins/volumen.yaml'
  register: result
  become: yes
  become_method: sudo

- debug:
    msg: '{{ result }}'