---

- name: 'Copio archivo Deploy App jenkins.yamll'
  copy:
    src: 'jenkins.yaml'
    dest: '/tmp/jenkins/'
  become: yes
  become_method: sudo


- name: Despliego Aplicacion, resultset y Servicios
  command: 'kubectl apply -f /tmp/jenkins/jenkins.yaml'
  register: result
  become: yes
  become_method: sudo

- debug:
    msg: '{{ result }}'
