---

- name: 'Copio archivo Deploy jenkins-services.yaml'
  copy:
    src: 'jenkins-services.yaml'
    dest: '/root/kube_deploy/jenkins_ok/'
  become: yes
  become_method: sudo


- name: Despliego tls
  command: 'kubectl apply -f /root/kube_deploy/jenkins_ok/jenkins-services.yaml'
  register: result
  become: yes
  become_method: sudo

- debug:
    msg: '{{ result }}'