---

- name: 'Copio archivo Deploy jenkins-services.yaml'
  copy:
    src: 'jenkins-services.yaml'
    dest: '/tmp/jenkins/'
  become: yes
  become_method: sudo


- name: Despliego tls
  command: 'kubectl apply -f /tmp/jenkins/jenkins-services.yaml'
  register: result
  become: yes
  become_method: sudo

- debug:
    msg: '{{ result }}'