---

- name: 'Copio archivo Deploy ingress ingress.yaml'
  copy:
    src: 'ingress.yaml'
    dest: '/root/kube_deploy/jenkins_ok/'
  become: yes
  become_method: sudo


- name: Despliego ingress
  command: 'kubectl apply -f /root/kube_deploy/jenkins_ok/ingress.yaml'
  register: result
  become: yes
  become_method: sudo

- debug:
    msg: '{{ result }}'