---

- name: 'Configura los puertos para el worker'
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    zone: public
  loop: '{{ ports_workers }}'
  #when: "'master' in ansible_hostname"
  become: yes
  become_method: sudo

#- name: Reiniciamos el servicio de firewall
#  systemd:
#    name: firewalld
#    state: reloaded
#  become: yes
#  become_method: sudo

- name: Obtengo las imagenes de firewalld
  command: systemctl restart firewalld
  register: result
  become: yes
  become_method: sudo
