---
#- name: Instalo IpRoute
#  dnf:
#    name: 'iproute-tc'
#    state: present
#  become: yes
#  become_method: sudo
  
- name: Instalo IpRoute
  command: yum install iproute-tc -y
  register: result
  become: yes
  become_method: sudo

#- name: 'Inicializa servicio y setea inicio automatico para servicio cri-o'
#  systemd:
#    name: 'crio'
#    state: started
#    enabled: yes
#  become: yes
#  become_method: sudo

